WIP: rework containers to organize / split by domain

diff --git a/container-bootstrap/bin/reset-all b/container-bootstrap/bin/reset-all
--- a/container-bootstrap/bin/reset-all
+++ b/container-bootstrap/bin/reset-all
@@ -7,10 +7,22 @@
 #
 #
 
-function kill_machines() {
-  verb=$1; shift
+function list_machines_by_domain() {
+  local domain=$1; shift
 
-  machinectl list -o json | jq -r '.[] | .machine' | xargs -P0 -n1 -i sudo machinectl $verb {};
+  machinectl list -o json | jq -r '.[] | .machine' | grep $domain | xargs
+}
+
+function kill_machines() {
+  local verb=$1; shift
+  local domain=$1; shift
+  local machines=$@;
+
+  running=$(list_machines_by_domain $domain)
+
+  for m in $machines; do
+    echo "$running" | grep -q $m && sudo machinectl $verb "$m.$domain"
+  done
 }
 
 function rem_state() {
@@ -19,7 +31,20 @@ function rem_state() {
   rm /etc/systemd/nspawn/*.${dom}.nspawn
 
   echo "Removing all in /var/lib/machines with domain $dom"
-  sudo find /var/lib/machines -maxdepth 1 -iname "*iaasbigdata.nextgen" -exec rm -Rf {} +
+  sudo find /var/lib/machines -maxdepth 1 -iname "*$dom" -exec rm -Rf {} +
+}
+
+function host_last() {
+  local h=$1; shift
+  local list=$@;
+
+  echo $list | grep -q $h && {
+    hh=$(echo $list | xargs -n1 | grep $h)
+    min=$(echo $list | xargs -n1 | grep -v $h | xargs)
+    list="$min $hh"
+  }
+
+  echo "$list"
 }
 
 [[ -z "$CON_DOMAIN" ]] && {
@@ -28,7 +53,19 @@ function rem_state() {
 }
 
 export TEMPORARY_CON_DIR=${TEMPORARY_CON_DIR:=/home/mdye/tmp}
-CON_HOSTS=$(find ./container-bootstrap/machine-scripts -iname "*.$CON_DOMAIN" -printf "%P\n" | xargs -i basename {} ".$CON_DOMAIN" | xargs)
+
+#TODO: fix this silly business
+CON_HOSTS=$(cd ./container-bootstrap/machine-scripts/$CON_DOMAIN; find * -maxdepth 0 | xargs)
+CON_HOSTS=$(host_last newhok $CON_HOSTS)
+CON_HOSTS=$(host_last mukoprospect $CON_HOSTS)
+
+# TODO: hook into bridge creation
+BRIDGE=$(echo $CON_DOMAIN | cut -d. -f1)
+
+sudo ip link show | grep -q $BRIDGE || {
+  echo "$BRIDGE does not exist, make sure to create it and start dnsmasq on it" >&2
+  exit 4
+}
 
 [[ -z "$CON_HOSTS" ]] && {
   (echo "Envvar CON_HOSTS not defined and must be" >&2)
@@ -45,22 +82,22 @@ CON_HOSTS=$(find ./container-bootstrap/machine-scripts -iname "*.$CON_DOMAIN" -p
   exit 1
 }
 
-echo "Waiting for termination of all containers..."
+echo "Waiting for termination of containers in $CON_DOMAIN..."
 
 ct=0
 while true; do
   sleep 1
   ((ct == 0)) || ( ((ct % 10 == 0)) && ((ct > 10)) ) && {
-    kill_machines terminate
+    kill_machines terminate $CON_DOMAIN $CON_HOSTS
   } || {
     ((ct > 200)) && {
-      echo "Unable to stop all machines"
+      echo "Unable to stop machines in $CON_DOMAIN"
       exit 4
     }
   }
 
   ct=$((ct+1))
-  machines=$(machinectl list -o json | jq -r '.[] | .machine')
+  machines=$(list_machines_by_domain $CON_DOMAIN)
 
   for c in $CON_HOSTS; do
     # continue 2 will continue outer level loop
@@ -83,7 +120,7 @@ done
   echo "REM_CON_STATE not set so leaving container content in-place"
 }
 
-export ENABLED_SCRIPTS=$(cd container-bootstrap/machine-scripts/; find -L . -type f -regex '.*[0-9]+\..*' -not -path "./common/disabled/*" -printf '%f\0' | xargs -0)
+export ENABLED_SCRIPTS=$(cd ./container-bootstrap; find -L * -regextype posix-egrep -regex ".*[0-9]+\..*" -and -executable -and -not -regex '.*disabled/.*' -exec basename -z {} \; -exec echo '' {} \; | sort -k1n | awk '{print $1}' | uniq | xargs)
 
 start=$(date -u +%s)
 echo $CON_HOSTS | sed 's, ,\n,g' | xargs -n1 -P0 -i -- sudo --preserve-env=ENABLED_SCRIPTS /bin/bash -c "(export TEMPDIR=$TEMPORARY_CON_DIR; ./container-bootstrap/build -f {}.$CON_DOMAIN -y -o /var/lib/machines -b $TEMPORARY_CON_DIR/nspawn-build/base -p cheese -s ./SSH-keys-and-certs/generated |& tee ./container-bootstrap/machines/{}-prov.out; echo 'Finished provisioning {}')"
@@ -96,7 +133,7 @@ for h in $CON_HOSTS; do
   cat > /etc/systemd/nspawn/$h.$CON_DOMAIN.nspawn <<EOF
 [Network]
 VirtualEthernet=yes
-Bridge=conhole
+Bridge=$BRIDGE
 EOF
 done
 
diff --git a/container-bootstrap/build b/container-bootstrap/build
--- a/container-bootstrap/build
+++ b/container-bootstrap/build
@@ -137,9 +137,9 @@ provision() {
 
 read -r -d '' dout <<EOF
 DEBUG options
+    fqdn: $FQDN
     yes: $YES
     tempd: $TEMPD
-    fqdn: $FQDN
     ssh_trust_mount: $SSH_TRUST_MOUNT
     outdir_base: $OUTDIR_BASE
     chroot_base: $CHROOT_BASE
@@ -248,27 +248,49 @@ EOF
   if [[ "$FQDN" != "" ]]; then
     echo "Copying machine scripts for $FQDN..."
 
-    cp -RfvpL $SOURCE/machine-scripts/common/* $TEMPD/setup/machine-scripts/
+    # determines the common destination passed to each setup script below
+    cp -RfvpL $SOURCE/machine-scripts/common $TEMPD/setup/machine-scripts/
 
-    if ls -A $SOURCE/machine-scripts/$FQDN 2>/dev/null; then
-      cp -RfvpL $SOURCE/machine-scripts/$FQDN/. $TEMPD/setup/machine-scripts/
-    fi
+    [[ -d $SOURCE/machine-scripts/$DOMAIN ]] && {
+      # may run many times b/c we're lazy so use rsync to get noop on subsequent calls
+      rsync -avzL --delete-after $SOURCE/machine-scripts/$DOMAIN $TEMPD/setup/machine-scripts/
+    } || {
+      echo "Warning: No machine scripts found for $SOURCE/machine-scripts/$DOMAIN"
+    }
 
     (cd $TEMPD/setup/machine-scripts;
-      scripts=$(find * -maxdepth 1 -type f | grep -P '^\d+\..*' | sort -t '.' -k1n)
-      (>&2 echo "INFO: scripts to execute in chroot: $scripts")
 
-      for f in $scripts; do
-        # TODO: handle this better, the names may clash
-        echo $ENABLED_SCRIPTS | grep -q "$f" && {
-          echo "Executing $f in $FQDN"
-          if ! chroot $TEMPD /bin/bash -x /setup/machine-scripts/$f "$HOST" "$DOMAIN" "/mnt/ssh_trust"; then
-            (>&2 echo "ERROR: Failure executing chroot $TEMPD /$f $HOST $DOMAIN /mnt/ssh_trust")
-            exit 6
-          fi
-        } || {
-          echo "Skipping $f on $FQDN because it's not in envvar ENABLED_SCRIPTS"
+      # these are all scripts, filtered in the loop before
+      scripts=$(find -L * -regextype posix-egrep -regex ".*[0-9]+\..*" -and -executable -and -not -regex '.*disabled/.*' -exec basename -z {} \; -exec echo '' {} \; | sort -k1n | awk '{print $2}' | xargs)
+      (>&2 echo "INFO: scripts to execute in $TEMPD/setup/machine-scripts: $scripts")
+
+      # scripts are full paths ordered by filename
+      for ff in $scripts; do
+        local name=$(basename $ff)
+        local chrootedpath=/setup/machine-scripts/$ff
+
+        # need to skip this script under a number of conditions:
+        # 1. not in ENABLED_SCRIPTS
+        # 2. not from either dir "common" -or- dir $DOMAIN/$HOST
+
+        echo $ENABLED_SCRIPTS | grep -q "$name" || {
+          echo "INFO: Skipping $chrootedpath on $FQDN because it's not in envvar ENABLED_SCRIPTS"
+          continue
         }
+
+        echo $ff | grep -qP "$DOMAIN/$HOST|common" || {
+          #echo "DEBUG: Skipping $ff on $FQDN because not in host/domain parent dirs or 'common'"
+          continue
+        }
+
+        # run script
+        echo "Executing $chrootedpath in $FQDN chroot"
+
+        chroot $TEMPD /bin/bash -x $chrootedpath "$HOST" "$DOMAIN" /mnt/ssh_trust /setup/machine-scripts/common || {
+          (>&2 echo "ERROR: Failure executing chroot $TEMPD $chrootedpath $HOST $DOMAIN /mnt/ssh_trust")
+          exit 6
+        }
+
       done)
     code=$?
   fi
diff --git a/container-bootstrap/setup/chroot-exec-base b/container-bootstrap/setup/chroot-exec-base
--- a/container-bootstrap/setup/chroot-exec-base
+++ b/container-bootstrap/setup/chroot-exec-base
@@ -1,5 +1,17 @@
 #!/bin/bash -ex
 
+function write_to_setup() {
+  local file=$1; shift
+  local urlbase=$1; shift
+
+  local dest=/setup/$file
+
+  [[ -f $dest ]] && return 0
+
+  local url=$urlbase/$file
+  curl -l $url > $dest || return 6
+}
+
 ROOT_PASS=$1; shift
 
 source /root/.bash_profile
@@ -34,12 +46,10 @@ done
 
 echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && /usr/sbin/locale-gen
 
-# TODO: parallelize these and check for matching the sha sum
+local_cache_url='http://10.109.39.196:9010'
 
-[[ ! -f /setup/hadoop-$HADOOP_VER.tar.gz ]] && {
-  curl -l http://10.109.39.196:9010/hadoop-$HADOOP_VER.tar.gz > /setup/hadoop-$HADOOP_VER.tar.gz || ((echo "Unable to fetch HADOOP" >&2) && exit 1)
-}
-
-[[ ! -f /setup/hbase-$HBASE_VER.tar.gz ]] && {
-  curl -l http://10.109.39.196:9010/hbase-$HBASE_VER-bin.tar.gz > /setup/hbase-$HBASE_VER-bin.tar.gz || ((echo "Unable to fetch HADOOP" >&2) && exit 1)
-}
+# TODO: check for matching sha sum
+write_to_setup $local_cache_url "hadoop-$HADOOP_VER.tar.gz" ||  ((echo "Unable to fetch Hadoop distribution" >&2) && exit 1) &
+write_to_setup $local_cache_url "hbase-$HBASE_VER.tar.gz" ||  ((echo "Unable to fetch HBase distribution" >&2) && exit 1) &
+write_to_setup $local_cache_url "kafka_$KAFKA_VER.tgz" ||  ((echo "Unable to fetch Kafka distribution" >&2) && exit 1) &
+write_to_setup $local_cache_url "apache-zookeeper-$ZOOKEEPER_VER-bin.tar.gz" ||  ((echo "Unable to fetch Zookeeper distribution" >&2) && exit 1) &
