added ability to enable only particular scripts with envvar

diff --git a/container-bootstrap/build b/container-bootstrap/build
--- a/container-bootstrap/build
+++ b/container-bootstrap/build
@@ -2,6 +2,11 @@
 
 SOURCE=$(realpath $(dirname $0))
 
+# made with something like this:
+#   cd container-bootstrap/machine-scripts/common/; find * -maxdepth 0 -regex '[0-9]+\..*' -type f | xargs
+# ... and then trimmed
+ENABLED_COMMON_SCRIPTS=${ENABLED_COMMON_SCRIPTS:="02.console-root-login 03.tzdata 05.systemd-networkd-dhcp 06.admin-user 08.ssh-trust"}
+
 usage() {
   echo "Usage: $0 -o /var/lib/machines [-f fqdn [-b /chroot/base/dir]]|[-g generate_base_dir_name] [-p root_password] [-s ssh_trust_mount]"
 }
@@ -253,11 +258,15 @@ EOF
       (>&2 echo "INFO: scripts to execute in chroot: $scripts")
 
       for f in $scripts; do
-        echo "Executing $f in $FQDN"
-        if ! chroot $TEMPD /bin/bash -x /setup/machine-scripts/$f "$HOST" "$DOMAIN" "/mnt/ssh_trust"; then
-          (>&2 echo "ERROR: Failure executing chroot $TEMPD /$f $HOST $DOMAIN /mnt/ssh_trust")
-          exit 6
-        fi
+        echo $ENABLED_COMMON_SCRIPTS | grep -q "$f" && {
+          echo "Executing $f in $FQDN"
+          if ! chroot $TEMPD /bin/bash -x /setup/machine-scripts/$f "$HOST" "$DOMAIN" "/mnt/ssh_trust"; then
+            (>&2 echo "ERROR: Failure executing chroot $TEMPD /$f $HOST $DOMAIN /mnt/ssh_trust")
+            exit 6
+          fi
+        } || {
+          echo "Skipping $f on $FQDN because it's not in envvar ENABLED_COMMON_SCRIPTS"
+        }
       done)
     code=$?
   fi
